export const LOANER_BOOKING_OVERLAP = 'LOANER_BOOKING_OVERLAP';
export const LOANER_RETURN_BEFORE_HANDOVER = 'LOANER_RETURN_BEFORE_HANDOVER';
export const LOANER_ODOMETER_IN_INVALID = 'LOANER_ODOMETER_IN_INVALID';
export const LOANER_ALREADY_RETURNED = 'LOANER_ALREADY_RETURNED';
export const LOANER_INVALID_HANDOVER_STATE = 'LOANER_INVALID_HANDOVER_STATE';
export const LOANER_FORBIDDEN_WRITE = 'LOANER_FORBIDDEN_WRITE';

export const ACTIVE_LOANER_BOOKING_STATUSES = [
  'RESERVED',
  'HANDED_OVER',
] as const;
