services:
  neo4j:
    image: neo4j:5.18
    ports:
      - "7474:7474"
      - "7687:7687"
    env_file:
      - .env
    environment:
      NEO4J_AUTH: ${NEO4J_USERNAME:?err}/${NEO4J_PASSWORD:?err}
      NEO4J_USERNAME: ${NEO4J_USERNAME:?err}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD:?err}
    volumes:
      - ./data:/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "cypher-shell -u $${NEO4J_USERNAME} -p $${NEO4J_PASSWORD} 'RETURN 1' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
