import test from 'node:test';
import assert from 'node:assert/strict';

import { validateTenantDump } from './verify-dump.mjs';

const tenantId = '11111111-1111-4111-8111-111111111111';
const manifest = {
  tables: ['tenant_records', 'fitments'],
};

function dumpFor(sourceTenantId = tenantId, body = '') {
  return `-- Generated by tools/tenant-restore/export-tenant-data.sh.
-- TENANT_ID: ${sourceTenantId}
-- Every COPY source is tenant-filtered; this is not a pg_dump output.
\\if :{?tenant_restore_in_transaction}
\\else
BEGIN;
\\endif

COPY public."tenant_records" (id, tenant_id) FROM STDIN WITH (FORMAT csv);
${body}\\.

COPY public."fitments" (id, record_id) FROM STDIN WITH (FORMAT csv);
\\.

\\if :{?tenant_restore_in_transaction}
\\else
COMMIT;
\\endif
`;
}

test('accepts only a generated dump bound to the confirmed tenant', () => {
  assert.doesNotThrow(() =>
    validateTenantDump(dumpFor(), tenantId, manifest),
  );
});

test('rejects a dump bound to another tenant', () => {
  assert.throws(
    () => validateTenantDump(dumpFor('22222222-2222-4222-8222-222222222222'), tenantId, manifest),
    /dump tenant id does not match target/,
  );
});

test('rejects unexpected SQL and unexpected tables', () => {
  assert.throws(
    () =>
      validateTenantDump(
        `${dumpFor()}DROP TABLE tenants;\n`,
        tenantId,
        manifest,
      ),
    /unexpected dump content/,
  );
});
