#!/usr/bin/env node

import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';

import { buildTenantRestoreManifestFromFiles } from './tenant-schema.mjs';

const UUID_PATTERN =
  /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$/;

const allowedControlLines = new Set([
  '\\if :{?tenant_restore_in_transaction}',
  '\\else',
  '\\endif',
  'BEGIN;',
  'COMMIT;',
]);

export function validateTenantDump(content, tenantId, manifest) {
  if (!UUID_PATTERN.test(tenantId)) {
    throw new Error('target tenant id must be a UUID');
  }

  const lines = content.split(/\r?\n/);
  if (
    lines[0] !==
    '-- Generated by tools/tenant-restore/export-tenant-data.sh.'
  ) {
    throw new Error('unexpected dump content: missing exporter marker');
  }
  if (lines[1] !== `-- TENANT_ID: ${tenantId}`) {
    throw new Error('dump tenant id does not match target');
  }

  const copiedTables = [];
  let inCopy = false;
  for (const line of lines.slice(3)) {
    if (inCopy) {
      if (line === '\\.') inCopy = false;
      continue;
    }
    if (!line || line.startsWith('--') || allowedControlLines.has(line)) {
      continue;
    }

    const copyMatch = line.match(
      /^COPY public\."([^"]+)" \(.+\) FROM STDIN WITH \(FORMAT csv\);$/,
    );
    if (copyMatch) {
      const [, table] = copyMatch;
      if (!manifest.tables.includes(table)) {
        throw new Error(`unexpected dump table: ${table}`);
      }
      if (copiedTables.includes(table)) {
        throw new Error(`duplicate dump table: ${table}`);
      }
      copiedTables.push(table);
      inCopy = true;
      continue;
    }

    throw new Error(`unexpected dump content: ${line}`);
  }

  if (inCopy) throw new Error('unexpected dump content: unterminated COPY');
  if (
    copiedTables.length !== manifest.tables.length ||
    copiedTables.some((table, index) => table !== manifest.tables[index])
  ) {
    throw new Error('dump table set or order does not match manifest');
  }
}

if (process.argv[1] === import.meta.filename) {
  const [, , dumpPath, tenantId] = process.argv;
  if (!dumpPath || !tenantId) {
    process.stderr.write(
      'Usage: verify-dump.mjs <dump_sql_file> <tenant_id>\n',
    );
    process.exit(1);
  }

  const scriptDirectory = import.meta.dirname;
  const manifest = buildTenantRestoreManifestFromFiles(
    path.resolve(scriptDirectory, '../../apps/core-api/prisma/schema.prisma'),
    path.resolve(scriptDirectory, '../../apps/core-api/prisma/migrations'),
  );

  try {
    validateTenantDump(fs.readFileSync(dumpPath, 'utf8'), tenantId, manifest);
    process.stdout.write(`Tenant dump is bound to ${tenantId}.\n`);
  } catch (error) {
    process.stderr.write(`[tenant-restore] ${error.message}\n`);
    process.exitCode = 1;
  }
}
