export const AGENT_POLICY_AUDIT_SOURCE = 'agent_policy';
export const AGENT_POLICY_ENTITY_TYPE = 'AgentPolicyRule';

export const AGENT_POLICY_ERROR_CODES = {
  LOOSER_THAN_PLATFORM: 'AGENT_POLICY_LOOSER_THAN_PLATFORM',
  UNKNOWN_ACTION_TYPE: 'AGENT_POLICY_UNKNOWN_ACTION_TYPE',
} as const;
