export const IMPORT_MAX_FILE_BYTES = 10 * 1024 * 1024;
export const IMPORT_MAX_ROW_COUNT = 20_000;
export const IMPORT_JOB_RETENTION_DAYS = 180;

export const IMPORT_SOURCE = 'import';

export const IMPORT_ERROR_CODES = {
  FILE_TOO_LARGE: 'IMPORT_FILE_TOO_LARGE',
  ROW_LIMIT_EXCEEDED: 'IMPORT_ROW_LIMIT_EXCEEDED',
  EMPTY_FILE: 'IMPORT_EMPTY_FILE',
  INVALID_ENCODING: 'IMPORT_INVALID_ENCODING',
  JOB_NOT_FOUND: 'IMPORT_JOB_NOT_FOUND',
  JOB_ALREADY_APPLIED: 'IMPORT_JOB_ALREADY_APPLIED',
  JOB_STALE: 'IMPORT_JOB_STALE',
  APPLY_IN_PROGRESS: 'IMPORT_APPLY_IN_PROGRESS',
  INVALID_ENTITY_TYPE: 'IMPORT_INVALID_ENTITY_TYPE',
  INVALID_MAPPING: 'IMPORT_INVALID_MAPPING',
} as const;
