export const IMPORT_MAX_FILE_BYTES = 10 * 1024 * 1024;
export const IMPORT_MAX_ROW_COUNT = 20_000;
export const IMPORT_JOB_RETENTION_DAYS = 180;

export const IMPORT_SOURCE = 'import';

export const IMPORT_ERROR_CODES = {
  FILE_TOO_LARGE: 'IMPORT_FILE_TOO_LARGE',
  ROW_LIMIT_EXCEEDED: 'IMPORT_ROW_LIMIT_EXCEEDED',
  EMPTY_FILE: 'IMPORT_EMPTY_FILE',
  INVALID_ENCODING: 'IMPORT_INVALID_ENCODING',
  JOB_NOT_FOUND: 'IMPORT_JOB_NOT_FOUND',
  JOB_ALREADY_APPLIED: 'IMPORT_JOB_ALREADY_APPLIED',
  JOB_STALE: 'IMPORT_JOB_STALE',
  APPLY_IN_PROGRESS: 'IMPORT_APPLY_IN_PROGRESS',
  INVALID_ENTITY_TYPE: 'IMPORT_INVALID_ENTITY_TYPE',
  INVALID_MAPPING: 'IMPORT_INVALID_MAPPING',
  ROW_STALE: 'IMPORT_ROW_STALE',
  APPLY_FAILED: 'IMPORT_APPLY_FAILED',
  DUPLICATE_EXTERNAL_ID_IN_FILE: 'IMPORT_DUPLICATE_EXTERNAL_ID_IN_FILE',
  DUPLICATE_EMAIL_IN_FILE: 'IMPORT_DUPLICATE_EMAIL_IN_FILE',
  MAPPING_PROFILE_EXISTS: 'IMPORT_MAPPING_PROFILE_EXISTS',
  SUPPLIER_VENDOR_REQUIRED: 'IMPORT_SUPPLIER_VENDOR_REQUIRED',
  PRICE_JUMP_REQUIRES_ACCEPTANCE: 'IMPORT_PRICE_JUMP_REQUIRES_ACCEPTANCE',
  PRICE_JUMP_EXCEEDED: 'PRICE_JUMP_EXCEEDED',
  RRP_MISSING_FOR_MARGIN_RULE: 'RRP_MISSING_FOR_MARGIN_RULE',
  ARTICLE_NOT_FOUND: 'IMPORT_ARTICLE_NOT_FOUND',
  SUPPLIER_ARTICLE_NO_REQUIRED: 'IMPORT_SUPPLIER_ARTICLE_NO_REQUIRED',
  DESCRIPTION_REQUIRED: 'IMPORT_DESCRIPTION_REQUIRED',
  INVALID_COST_PRICE: 'IMPORT_INVALID_COST_PRICE',
  DUPLICATE_ARTICLE_NO_IN_FILE: 'IMPORT_DUPLICATE_ARTICLE_NO_IN_FILE',
  AMBIGUOUS_VENDOR: 'IMPORT_AMBIGUOUS_VENDOR',
} as const;
